-- ═══════════════════════════════════════════════════════════════════════════
-- Migration: 002 — Core Operational Tables
-- Rooms, Occupants, Bookings, Payments
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Room categories ───────────────────────────────────────────────────────────

create table room_categories (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references tenants(id) on delete cascade,
  name        text not null,           -- "Executive Single", "Standard Double"
  type        room_type not null,
  base_rate   integer not null check (base_rate >= 0),  -- pesewas (GHS × 100)
  rate_unit   text not null default 'semester' check (rate_unit in ('night','week','month','semester')),
  capacity    smallint not null default 1 check (capacity between 1 and 20),
  amenities   text[] not null default '{}',
  description text,
  image_urls  text[] not null default '{}',
  is_active   boolean not null default true,
  sort_order  smallint not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create trigger room_categories_updated_at
  before update on room_categories
  for each row execute function set_updated_at();

create index on room_categories (tenant_id);
create index on room_categories (tenant_id, is_active);

-- ── Rooms ─────────────────────────────────────────────────────────────────────

create table rooms (
  id                  uuid primary key default gen_random_uuid(),
  tenant_id           uuid not null references tenants(id) on delete cascade,
  category_id         uuid not null references room_categories(id),
  room_number         text not null,
  floor               smallint,
  block               text,
  status              room_status not null default 'available',
  housekeeping_status housekeeping_status not null default 'clean',
  notes               text,
  last_cleaned_at     timestamptz,
  last_inspected_at   timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  unique (tenant_id, room_number)
);

create trigger rooms_updated_at
  before update on rooms
  for each row execute function set_updated_at();

create index on rooms (tenant_id);
create index on rooms (tenant_id, status);
create index on rooms (tenant_id, housekeeping_status);
create index on rooms (category_id);

-- ── Occupants ─────────────────────────────────────────────────────────────────

create table occupants (
  id                 uuid primary key default gen_random_uuid(),
  tenant_id          uuid not null references tenants(id) on delete cascade,
  type               occupant_type not null default 'student',
  status             occupant_status not null default 'pending',

  -- Personal
  first_name         text not null,
  last_name          text not null,
  other_names        text,
  gender             gender_type,
  date_of_birth      date,
  national_id_type   id_type,
  national_id_number text,
  photo_url          text,

  -- Contact
  phone              text not null,
  alternate_phone    text,
  email              text,
  home_address       text,
  region_of_origin   text,  -- Ghana region

  -- Student-specific
  institution        text,
  student_id         text,
  programme          text,
  year_of_study      smallint check (year_of_study between 1 and 10),
  semester           text check (semester in ('first','second','summer')),

  -- Emergency contact (JSONB for flexibility)
  emergency_contact  jsonb,

  notes              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create trigger occupants_updated_at
  before update on occupants
  for each row execute function set_updated_at();

create index on occupants (tenant_id);
create index on occupants (tenant_id, status);
create index on occupants (tenant_id, type);
-- Trigram index for name search (supports fuzzy "did you mean?" search)
create index on occupants using gin ((first_name || ' ' || last_name) gin_trgm_ops);

-- ── Bookings ──────────────────────────────────────────────────────────────────

create table bookings (
  id                  uuid primary key default gen_random_uuid(),
  tenant_id           uuid not null references tenants(id) on delete cascade,
  booking_ref         text not null,   -- generated by app: ABR-2024-001847
  occupant_id         uuid not null references occupants(id),
  room_id             uuid not null references rooms(id),

  status              booking_status not null default 'pending_payment',
  source              booking_source not null default 'walk_in',

  check_in_date       date not null,
  check_out_date      date not null,
  actual_check_in     timestamptz,
  actual_check_out    timestamptz,

  -- Pricing (all pesewas)
  rate_per_unit       integer not null check (rate_per_unit >= 0),
  rate_unit           text not null default 'semester',
  total_amount        integer not null check (total_amount >= 0),
  discount_amount     integer not null default 0 check (discount_amount >= 0),
  discount_reason     text,
  tax_amount          integer not null default 0 check (tax_amount >= 0),
  final_amount        integer not null generated always as (total_amount - discount_amount + tax_amount) stored,

  payment_status      payment_status not null default 'unpaid',
  paid_amount         integer not null default 0 check (paid_amount >= 0),

  semester            text,
  academic_year       text,

  notes               text,
  cancelled_at        timestamptz,
  cancellation_reason text,
  created_by          uuid references auth.users(id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  unique (tenant_id, booking_ref),

  -- Prevent double-booking: two confirmed bookings cannot overlap on the same room
  constraint no_double_booking exclude using gist (
    room_id with =,
    daterange(check_in_date, check_out_date, '[)') with &&
  ) where (status in ('confirmed', 'checked_in'))
);

create trigger bookings_updated_at
  before update on bookings
  for each row execute function set_updated_at();

create index on bookings (tenant_id);
create index on bookings (tenant_id, status);
create index on bookings (tenant_id, payment_status);
create index on bookings (occupant_id);
create index on bookings (room_id);
create index on bookings (check_in_date, check_out_date);

-- ── Booking payments ──────────────────────────────────────────────────────────

create table booking_payments (
  id                   uuid primary key default gen_random_uuid(),
  tenant_id            uuid not null references tenants(id) on delete cascade,
  booking_id           uuid not null references bookings(id) on delete cascade,
  amount               integer not null check (amount > 0),  -- pesewas
  method               payment_method not null,
  reference            text,
  paystack_reference   text unique,
  status               text not null default 'pending' check (status in ('pending','success','failed','reversed')),
  paid_at              timestamptz,
  received_by          uuid references auth.users(id),
  notes                text,
  created_at           timestamptz not null default now()
);

create index on booking_payments (tenant_id);
create index on booking_payments (booking_id);
create index on booking_payments (paystack_reference) where paystack_reference is not null;

-- ── Trigger: update booking.paid_amount when payments change ─────────────────

create or replace function sync_booking_paid_amount()
returns trigger language plpgsql security definer as $$
begin
  update bookings
  set    paid_amount = (
           select coalesce(sum(amount), 0)
           from   booking_payments
           where  booking_id = coalesce(new.booking_id, old.booking_id)
             and  status = 'success'
         ),
         payment_status = case
           when coalesce(sum(bp.amount) filter (where bp.status = 'success'), 0) = 0
             then 'unpaid'
           when coalesce(sum(bp.amount) filter (where bp.status = 'success'), 0) >= b.final_amount
             then 'paid'
           else 'partial'
         end
  from   bookings b
  left join booking_payments bp on bp.booking_id = b.id
  where  b.id = coalesce(new.booking_id, old.booking_id)
  group  by b.id;

  return coalesce(new, old);
end;
$$;

create trigger booking_payments_sync
  after insert or update or delete on booking_payments
  for each row execute function sync_booking_paid_amount();
